# Generated by Django 4.0.1 on 2022-01-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Id_soutenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.soutenance'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='encadreurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.encadreur'),
        ),
    ]
