# Generated by Django 4.0.1 on 2022-01-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_stage_id_soutenance_alter_stage_encadreurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheevaluation',
            name='Stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.stage'),
        ),
    ]
